/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chima
 */
public class home_Theater extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home_Theater() {
        initComponents();
    }
    String userhome = "";
    home_Theater(String user) {
        this();
        txtuser.setText(user);
        userhome = txtuser.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        txtUsername = new javax.swing.JPanel();
        btmovie = new javax.swing.JLabel();
        btexit = new javax.swing.JLabel();
        btmini = new javax.swing.JLabel();
        btmovie_next = new javax.swing.JLabel();
        btmovie_special = new javax.swing.JLabel();
        btmovie_kids = new javax.swing.JLabel();
        bttheater = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btmovie_now = new javax.swing.JLabel();
        btPromotion1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(58, 71, 80));
        txtUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmovie.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie.setForeground(new java.awt.Color(238, 238, 238));
        btmovie.setText("ภาพยนตร์");
        btmovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovieMouseClicked(evt);
            }
        });
        txtUsername.add(btmovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 77, -1));

        btexit.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btexit.setForeground(new java.awt.Color(238, 238, 238));
        btexit.setText("X");
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btexitMouseClicked(evt);
            }
        });
        txtUsername.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 12, -1));

        btmini.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmini.setForeground(new java.awt.Color(238, 238, 238));
        btmini.setText("-");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        txtUsername.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 24, -1));

        btmovie_next.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next.setText("โปรแกรมหน้า");
        btmovie_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_nextMouseClicked(evt);
            }
        });
        txtUsername.add(btmovie_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 90, 77, -1));

        btmovie_special.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_special.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_special.setText("รอบฉายพิเศษ");
        btmovie_special.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_specialMouseClicked(evt);
            }
        });
        txtUsername.add(btmovie_special, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 90, -1));

        btmovie_kids.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_kids.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_kids.setText("คิดส์ ซีนีมา");
        btmovie_kids.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_kidsMouseClicked(evt);
            }
        });
        txtUsername.add(btmovie_kids, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 90, 81, -1));

        bttheater.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        bttheater.setForeground(new java.awt.Color(215, 35, 35));
        bttheater.setText("โรงภาพยนตร์");
        bttheater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttheaterMouseClicked(evt);
            }
        });
        txtUsername.add(bttheater, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, -1, -1));

        txtuser.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        txtuser.setForeground(new java.awt.Color(238, 238, 238));
        txtuser.setText("USER");
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
        });
        txtUsername.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 100, -1));

        jPanel1.setBackground(new java.awt.Color(215, 35, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        txtUsername.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 121, 589, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/mini_logo.png"))); // NOI18N
        txtUsername.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 13, -1, -1));

        btmovie_now.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_now.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_now.setText("กำลังฉาย");
        btmovie_now.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_nowMouseClicked(evt);
            }
        });
        txtUsername.add(btmovie_now, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 90, 66, -1));

        btPromotion1.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btPromotion1.setForeground(new java.awt.Color(238, 238, 238));
        btPromotion1.setText("โปรโมชั่น");
        btPromotion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPromotion1MouseClicked(evt);
            }
        });
        txtUsername.add(btPromotion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, -1, -1));

        jLabel2.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username : ");
        txtUsername.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/TheaterMap.png"))); // NOI18N
        txtUsername.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("โรงหนังจะอยู๋ตามหมายเลข 1 - 12");
        txtUsername.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 300, -1));

        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 726));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseClicked
        // Click to Exit Programs.
        System.exit(0);
    }//GEN-LAST:event_btexitMouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        // Click Minisize Windows.
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void btmovie_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_nextMouseClicked
        // Movie Next!
        home_newmovie call = new home_newmovie(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btmovie_nextMouseClicked

    private void btmovie_specialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_specialMouseClicked
        // Movie Special!
        home_newspecial call = new home_newspecial(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btmovie_specialMouseClicked

    private void btmovie_kidsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_kidsMouseClicked
        // Movie Kid!
        home_newkid call = new home_newkid(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btmovie_kidsMouseClicked

    private void btmovie_nowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_nowMouseClicked
        // MOvie Now!
        home call = new home(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btmovie_nowMouseClicked

    private void btmovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovieMouseClicked
        // Movie
        home call = new home(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btmovieMouseClicked

    private void bttheaterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttheaterMouseClicked
        // Theater!
        home_Theater call = new home_Theater(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_bttheaterMouseClicked

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked

    }//GEN-LAST:event_txtuserMouseClicked

    private void btPromotion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPromotion1MouseClicked
        // Promotion
        home_Promotion call = new home_Promotion(userhome);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btPromotion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_Theater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_Theater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_Theater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_Theater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_Theater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btPromotion1;
    private javax.swing.JLabel btexit;
    private javax.swing.JLabel btmini;
    private javax.swing.JLabel btmovie;
    private javax.swing.JLabel btmovie_kids;
    private javax.swing.JLabel btmovie_next;
    private javax.swing.JLabel btmovie_now;
    private javax.swing.JLabel btmovie_special;
    private javax.swing.JLabel bttheater;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel txtUsername;
    private javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
