/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chima
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btexit = new javax.swing.JLabel();
        btmini = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btsignin = new javax.swing.JLabel();
        btnewaccount = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txtUsername.setBackground(new java.awt.Color(58, 71, 80));
        txtUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Username");
        txtUsername.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 228, 77, -1));

        jLabel2.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Password");
        txtUsername.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 286, 77, -1));

        txtusername.setBackground(new java.awt.Color(238, 238, 238));
        txtusername.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        txtUsername.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 212, 32));

        jLabel3.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Click here to create a ");
        txtUsername.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 387, -1, 24));

        jPanel4.setBackground(new java.awt.Color(215, 35, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Movie/POSTER_01.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        txtUsername.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btexit.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btexit.setForeground(new java.awt.Color(238, 238, 238));
        btexit.setText("X");
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btexitMouseClicked(evt);
            }
        });
        txtUsername.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 12, -1));

        btmini.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmini.setForeground(new java.awt.Color(238, 238, 238));
        btmini.setText("-");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        txtUsername.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 24, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/TheaterLOGO.png"))); // NOI18N
        txtUsername.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 161));

        btsignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/signin_logo.png"))); // NOI18N
        btsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsigninMouseClicked(evt);
            }
        });
        txtUsername.add(btsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        btnewaccount.setBackground(new java.awt.Color(215, 35, 35));
        btnewaccount.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        btnewaccount.setForeground(new java.awt.Color(215, 35, 35));
        btnewaccount.setText("new account. ");
        btnewaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnewaccountMouseClicked(evt);
            }
        });
        txtUsername.add(btnewaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 387, 83, 24));

        txtpassword.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        txtUsername.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 212, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseClicked
        // Click to Exit Programs.
        System.exit(0);
    }//GEN-LAST:event_btexitMouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        // Click Minisize Windows. 
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void btnewaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnewaccountMouseClicked
        // Click to Go to Register Page.
        register call = new register();
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btnewaccountMouseClicked
    
    String user = "";
    private void btsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsigninMouseClicked
        //Read Files Register to LoginPage.
       try{
           String username = txtusername.getText(); // Get Value
           String password = new String(txtpassword.getPassword()); // Get Value
           //Start ReadFile............................................
           FileReader reader = new FileReader("Register.txt");
           BufferedReader br = new BufferedReader(reader);
           String line  , user , pass ; //Set String to Value.
            while ((line = br.readLine()) != null) { //Single Line Read.
                user = line.split(" ")[0].toLowerCase();
                pass = line.split(" ")[1].toLowerCase();
                if(user.equals(username)&& pass.equals(password)){//check
                    JOptionPane.showMessageDialog(null,"Login Success!!");
                    setVisible(false);
                    //Go to HomePage.................................
                    user = txtusername.getText();
                    home call = new home(user);
                    call.setVisible(true);
                    setLocationRelativeTo(null);
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    pack();
                    dispose();
                    //................................................
                    break;
                }
           }
           reader.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error");
           setVisible(false);
           new login().setVisible(true);
       }
        
    }//GEN-LAST:event_btsigninMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btexit;
    private javax.swing.JLabel btmini;
    private javax.swing.JLabel btnewaccount;
    private javax.swing.JLabel btsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel txtUsername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
