/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList; // import the ArrayList class
import javax.swing.ImageIcon;

/**
 *
 * @author chima
 */
public class movie_05 extends javax.swing.JFrame {

    /**
     * Creates new form movie_01
     */
    public movie_05() {
        initComponents();
    jLabel1.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel2.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel3.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel4.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel5.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel6.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel7.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel8.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel9.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel10.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel11.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel12.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel13.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel14.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel15.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel16.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel17.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel18.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel19.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel20.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel21.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel22.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel23.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel24.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel25.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel26.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel27.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel28.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel29.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel30.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel31.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel32.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel33.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel34.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel35.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel36.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel37.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel38.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel39.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel40.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel41.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel42.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel43.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel44.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel45.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel46.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel47.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    jLabel48.setIcon(new ImageIcon("src\\Picture\\seat_blue.png")); 
    jLabel49.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
    jLabel50.setIcon(new ImageIcon("src\\Picture\\seat_blue.png"));
    }
    String usermovie1 = "";
    movie_05(String userhome) {
        this();
        txtuserm1.setText(userhome);
        usermovie1 = txtuserm1.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btmovie_next6 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btmovie_next7 = new javax.swing.JLabel();
        btmovie_next8 = new javax.swing.JLabel();
        btmovie_next9 = new javax.swing.JLabel();
        btmovie_next10 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btback1 = new javax.swing.JLabel();
        btmovie_next11 = new javax.swing.JLabel();
        btmovie_next12 = new javax.swing.JLabel();
        btmovie_next13 = new javax.swing.JLabel();
        btmovie_next14 = new javax.swing.JLabel();
        btfinish = new javax.swing.JLabel();
        btexit = new javax.swing.JLabel();
        btmini = new javax.swing.JLabel();
        btmovie_next18 = new javax.swing.JLabel();
        btmovie_next19 = new javax.swing.JLabel();
        btmovie_next20 = new javax.swing.JLabel();
        btmovie_next21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtuserm1 = new javax.swing.JLabel();
        btmovie_next16 = new javax.swing.JLabel();
        prices = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txtUsername.setBackground(new java.awt.Color(58, 71, 80));
        txtUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(48, 56, 65));

        btmovie_next6.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next6.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next6.setText("จอภาพยนตร์");
        btmovie_next6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(btmovie_next6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmovie_next6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtUsername.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 548, -1));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/TAB.png"))); // NOI18N
        txtUsername.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 548, -1));

        jPanel2.setBackground(new java.awt.Color(48, 56, 65));

        btmovie_next7.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next7.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next7.setText("Kung Fu Panda");
        btmovie_next7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next7MouseClicked(evt);
            }
        });

        btmovie_next8.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next8.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next8.setText("21/04/2022 ");
        btmovie_next8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next8MouseClicked(evt);
            }
        });

        btmovie_next9.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next9.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next9.setText("เด็กและครอบครัว/ตลก");
        btmovie_next9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next9MouseClicked(evt);
            }
        });

        btmovie_next10.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next10.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next10.setText("1 ชั่วโมง 32 นาที");
        btmovie_next10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next10MouseClicked(evt);
            }
        });

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Movie/T05.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmovie_next7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmovie_next8)
                    .addComponent(btmovie_next9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmovie_next10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btmovie_next7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmovie_next8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmovie_next9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmovie_next10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUsername.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 540, -1));

        btback1.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btback1.setForeground(new java.awt.Color(238, 238, 238));
        btback1.setText("< ย้อนกลับ ");
        btback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btback1MouseClicked(evt);
            }
        });
        txtUsername.add(btback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 602, 77, -1));

        btmovie_next11.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next11.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next11.setText("A");
        txtUsername.add(btmovie_next11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        btmovie_next12.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next12.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next12.setText("B");
        txtUsername.add(btmovie_next12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        btmovie_next13.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next13.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next13.setText("C");
        txtUsername.add(btmovie_next13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        btmovie_next14.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next14.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next14.setText("D");
        txtUsername.add(btmovie_next14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        btfinish.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btfinish.setForeground(new java.awt.Color(238, 238, 238));
        btfinish.setText("เสร็จสิ้น >");
        btfinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btfinishMouseClicked(evt);
            }
        });
        txtUsername.add(btfinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 602, -1, -1));

        btexit.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btexit.setForeground(new java.awt.Color(238, 238, 238));
        btexit.setText("X");
        btexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btexitMouseClicked(evt);
            }
        });
        txtUsername.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 12, -1));

        btmini.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmini.setForeground(new java.awt.Color(238, 238, 238));
        btmini.setText("-");
        btmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btminiMouseClicked(evt);
            }
        });
        txtUsername.add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 24, -1));

        btmovie_next18.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next18.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next18.setText("A");
        txtUsername.add(btmovie_next18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        btmovie_next19.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next19.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next19.setText("B");
        txtUsername.add(btmovie_next19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        btmovie_next20.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next20.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next20.setText("C");
        txtUsername.add(btmovie_next20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        btmovie_next21.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next21.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next21.setText("D");
        txtUsername.add(btmovie_next21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        jLabel1.setText("A1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 28, 30));

        jLabel2.setText("A2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 28, 30));

        jLabel3.setText("A3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 28, 30));

        jLabel4.setText("A4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 28, 30));

        jLabel5.setText("A5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 28, 30));

        jLabel6.setText("A6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 28, 30));

        jLabel7.setText("A7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 28, 30));

        jLabel8.setText("A8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 28, 30));

        jLabel9.setText("A9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 28, 30));

        jLabel10.setText("A11");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 28, 30));

        jLabel11.setText("A12");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 30, 30));

        jLabel12.setText("A10");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 28, 30));

        jLabel14.setText("B2");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 28, 30));

        jLabel15.setText("B3");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 28, 30));

        jLabel16.setText("B4");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 28, 30));

        jLabel17.setText("B5");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 28, 30));

        jLabel18.setText("B6");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 28, 30));

        jLabel19.setText("B7");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 28, 30));

        jLabel20.setText("B8");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 28, 30));

        jLabel21.setText("B9");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 28, 30));

        jLabel22.setText("B10");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 28, 30));

        jLabel23.setText("B11");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 28, 30));

        jLabel24.setText("B12");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 30, 30));

        jLabel25.setText("C1");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 28, 30));

        jLabel26.setText("C2");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 28, 30));

        jLabel28.setText("C4");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 28, 30));

        jLabel29.setText("C5");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 28, 30));

        jLabel30.setText("C6");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 28, 30));

        jLabel31.setText("C7");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 28, 30));

        jLabel32.setText("C8");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 28, 30));

        jLabel33.setText("C9");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 28, 30));

        jLabel34.setText("C10");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 28, 30));

        jLabel35.setText("C11");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 28, 30));

        jLabel36.setText("C12");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 30, 30));

        jLabel38.setText("D2");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 28, 30));

        jLabel39.setText("D3");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 28, 30));

        jLabel40.setText("D4");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 28, 30));

        jLabel41.setText("D5");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 28, 30));

        jLabel42.setText("D6");
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 28, 30));

        jLabel43.setText("D7");
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 28, 30));

        jLabel44.setText("D8");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 28, 30));

        jLabel45.setText("D9");
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 28, 30));

        jLabel46.setText("D10");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 28, 30));

        jLabel47.setText("D11");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 28, 30));

        jLabel48.setText("A12");
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 30, 30));

        price.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("150");
        txtUsername.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, -1, -1));

        jLabel13.setText("B1");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 28, 30));

        jLabel27.setText("C3");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 28, 30));

        jLabel37.setText("D1");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        txtUsername.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 28, 30));

        txtuserm1.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        txtuserm1.setForeground(new java.awt.Color(238, 238, 238));
        txtuserm1.setText("User  ");
        txtuserm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserm1MouseClicked(evt);
            }
        });
        txtUsername.add(txtuserm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, -1));

        btmovie_next16.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        btmovie_next16.setForeground(new java.awt.Color(238, 238, 238));
        btmovie_next16.setText("Username :  ");
        btmovie_next16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmovie_next16MouseClicked(evt);
            }
        });
        txtUsername.add(btmovie_next16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        prices.setFont(new java.awt.Font("LilyUPC", 0, 24)); // NOI18N
        prices.setForeground(new java.awt.Color(255, 255, 255));
        prices.setText("250");
        txtUsername.add(prices, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        jLabel49.setText("A1");
        txtUsername.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 30, -1));

        jLabel50.setText("A1");
        txtUsername.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btback1MouseClicked
        // Back to Home Page.
        home call = new home(usermovie1);
        call.setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        dispose();
    }//GEN-LAST:event_btback1MouseClicked

    private void btmovie_next10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next10MouseClicked

    private void btmovie_next9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next9MouseClicked

    private void btmovie_next8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next8MouseClicked

    private void btmovie_next7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next7MouseClicked

    private void btmovie_next6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next6MouseClicked

    private void btminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btminiMouseClicked
        // Click Minisize Windows.
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btminiMouseClicked

    private void btexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btexitMouseClicked
        // Click to Exit Programs.
        System.exit(0);
    }//GEN-LAST:event_btexitMouseClicked

    private void btfinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btfinishMouseClicked
        // TODO add your handling code here:
        new Movie_Ticket5(seats,total,usermovie1).setVisible(true);
    }//GEN-LAST:event_btfinishMouseClicked

    int total = 0;
    String seats = "";
    // Value of Seat.
    int buyA1,buyA2,buyA3,buyA4,buyA5,buyA6,buyA7,buyA8,buyA9,buyA10,buyA11,buyA12;
    int buyB1,buyB2,buyB3,buyB4,buyB5,buyB6,buyB7,buyB8,buyB9,buyB10,buyB11,buyB12;
    int buyC1,buyC2,buyC3,buyC4,buyC5,buyC6,buyC7,buyC8,buyC9,buyC10,buyC11,buyC12;
    int buyD1,buyD2,buyD3,buyD4,buyD5,buyD6,buyD7,buyD8,buyD9,buyD10,buyD11,buyD12;
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(buyA1 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A1\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA1++;
            jLabel1.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+jLabel1.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA1 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel1.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(buyA2 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A2\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA2++;
            jLabel2.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel2.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA2 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel2.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(buyA3 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A3\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA3++;
            jLabel3.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel3.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA3 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel3.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(buyA4 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A4\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA4++;
            jLabel4.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel4.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA4 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel4.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(buyA5 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A5\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA5++;
            jLabel5.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel5.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA5 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel5.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(buyA6 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A6\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA6++;
            jLabel6.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel6.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA6 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel6.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(buyA7 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A7\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA7++;
            jLabel7.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel7.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA7 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel7.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(buyA8 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A8\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA8++;
            jLabel8.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel8.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA8 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel8.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(buyA9 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A9\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA9++;
            jLabel9.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel9.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA9 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel9.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if(buyA10 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A10\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA10++;
            jLabel10.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel10.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA10 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel10.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if(buyA11 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A11\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA11++;
            jLabel11.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel11.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA11 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel11.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(buyA12 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = A12\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyA12++;
            jLabel12.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel12.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyA12 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel12.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(buyB1 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B1\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB1++;
            jLabel13.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel13.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB1 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel13.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if(buyB2 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B2\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB2++;
            jLabel14.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel14.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB2 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel14.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if(buyB3 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B3\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB3++;
            jLabel15.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel15.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB3 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel15.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if(buyB4 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B4\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB4++;
            jLabel16.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel16.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB4 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel16.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if(buyB5 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B5\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB5++;
            jLabel17.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel17.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB5 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel17.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        if(buyB6 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B6\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB6++;
            jLabel18.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel18.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB6 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel18.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if(buyB7 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B7\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB7++;
            jLabel19.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel19.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB7 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel19.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if(buyB8 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B8\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB8++;
            jLabel20.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel20.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB8 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel20.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if(buyB9 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B9\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB9++;
            jLabel21.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel21.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB9 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel21.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        if(buyB10 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B10\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB10++;
            jLabel22.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel22.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB10 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel22.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if(buyB11 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B11\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB11++;
            jLabel23.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel23.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB11 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel23.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        if(buyB12 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = B12\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyB12++;
            jLabel24.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel24.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyB12 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel24.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        if(buyC1 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C1\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC1++;
            jLabel25.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel25.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC1 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel25.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        if(buyC2 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C2\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC2++;
            jLabel26.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel26.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC2 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel26.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        if(buyC3 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C3\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC3++;
            jLabel27.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel27.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC3 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel27.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        if(buyC4 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C4\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC4++;
            jLabel28.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel28.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC4 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel28.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        if(buyC5 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C5\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC5++;
            jLabel29.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel29.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC5 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel29.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        if(buyC6 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C6\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC6++;
            jLabel30.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel30.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC6 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel30.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        if(buyC7 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C7\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC7++;
            jLabel31.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel31.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC7 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel31.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        if(buyC8 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C8\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC8++;
            jLabel32.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel32.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC8 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel32.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        if(buyC9 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C9\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC9++;
            jLabel33.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel33.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC9 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel33.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        if(buyC10 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C10\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC10++;
            jLabel34.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel34.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC10 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel34.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        if(buyC11 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C11\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC11++;
            jLabel35.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel35.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC11 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel35.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        if(buyC12 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = C12\n Price = 150 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyC12++;
            jLabel36.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel36.getText();
            int sum = Integer.parseInt(price.getText());
            total = total+sum;
            }
        else if(buyC12 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel36.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        if(buyD1 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D1\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD1++;
            jLabel37.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel37.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD1 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel37.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        if(buyD2 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D2\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD2++;
            jLabel38.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel38.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD2 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel38.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        if(buyD3 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D3\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD3++;
            jLabel39.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel39.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD3 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel39.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        if(buyD4 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D4\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD4++;
            jLabel40.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel40.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD4 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel40.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        if(buyD5 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D5\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD5++;
            jLabel41.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel41.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD5 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel41.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        if(buyD6 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D6\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD6++;
            jLabel42.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel42.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD6 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel42.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        if(buyD7 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D7\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD7++;
            jLabel43.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel43.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD6 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel43.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        if(buyD8 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D8\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD8++;
            jLabel44.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel44.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD8 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel44.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        if(buyD9 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D9\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD9++;
            jLabel45.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel45.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD9 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel45.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        if(buyD10 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D10\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD10++;
            jLabel46.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel46.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD10 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel46.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        if(buyD11 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D11\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD11++;
            jLabel47.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel47.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD11 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel47.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        if(buyD12 == 0) {
        //JOptionPane YES/NO
        int confirm = JOptionPane.showConfirmDialog(this,"SEAT = D12\n Price = 250 Baht.","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            buyD12++;
            jLabel48.setIcon(new ImageIcon("src\\Picture\\seat_green.png"));
            seats = seats+"  "+jLabel48.getText();
            int sum = Integer.parseInt(prices.getText());
            total = total+sum;
            }
        else if(buyD12 > 0) {
            JOptionPane.showMessageDialog(null,"Seat was purchased.");
            }
        else if(confirm==JOptionPane.NO_OPTION){
            jLabel48.setIcon(new ImageIcon("src\\Picture\\seat_red.png"));
            }
        }
    }//GEN-LAST:event_jLabel48MouseClicked

    private void txtuserm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserm1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserm1MouseClicked

    private void btmovie_next16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmovie_next16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btmovie_next16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btback1;
    private javax.swing.JLabel btexit;
    private javax.swing.JLabel btfinish;
    private javax.swing.JLabel btmini;
    private javax.swing.JLabel btmovie_next10;
    private javax.swing.JLabel btmovie_next11;
    private javax.swing.JLabel btmovie_next12;
    private javax.swing.JLabel btmovie_next13;
    private javax.swing.JLabel btmovie_next14;
    private javax.swing.JLabel btmovie_next16;
    private javax.swing.JLabel btmovie_next18;
    private javax.swing.JLabel btmovie_next19;
    private javax.swing.JLabel btmovie_next20;
    private javax.swing.JLabel btmovie_next21;
    private javax.swing.JLabel btmovie_next6;
    private javax.swing.JLabel btmovie_next7;
    private javax.swing.JLabel btmovie_next8;
    private javax.swing.JLabel btmovie_next9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel price;
    private javax.swing.JLabel prices;
    private javax.swing.JPanel txtUsername;
    private javax.swing.JLabel txtuserm1;
    // End of variables declaration//GEN-END:variables
}
